"""
04_cohort_retention.py — Cohort / Retention Analysis

Groups customers into monthly acquisition cohorts by first-order month,
then tracks what share of each cohort places another order in each
subsequent month. Saves a retention matrix CSV and a heatmap.
"""
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

CLEANED = "../data/cleaned"
CHARTS = "../eda_charts"

fact = pd.read_csv(f"{CLEANED}/fact_orders.csv", parse_dates=["order_date"])
fact["order_month"] = fact["order_date"].dt.to_period("M")

first_order = fact.groupby("user_id")["order_month"].min().rename("cohort_month")
fact = fact.join(first_order, on="user_id")
fact["period_number"] = (fact["order_month"] - fact["cohort_month"]).apply(lambda x: x.n)

cohort_data = fact.groupby(["cohort_month", "period_number"])["user_id"].nunique().reset_index()
cohort_sizes = cohort_data[cohort_data.period_number == 0].set_index("cohort_month")["user_id"]

retention = cohort_data.pivot(index="cohort_month", columns="period_number", values="user_id")
retention_pct = retention.divide(cohort_sizes, axis=0) * 100

print("Cohort sizes (customers acquired per month):")
print(cohort_sizes.to_string())

print("\nRetention % matrix (first 12 periods, first 12 cohorts):")
print(retention_pct.iloc[:12, :12].round(1).to_string())

# overall retention curve (average % retained at each period, weighted by cohort size)
weighted = (retention.fillna(0).multiply(1)).sum(axis=0)
overall_base = cohort_sizes.sum()
overall_retention = (weighted / overall_base * 100)
# but period 0 always =100% by construction only if every cohort survives to period0; use proper weighted avg instead
period_totals = retention.sum(axis=0, skipna=True)
period_bases = cohort_sizes.sum()
overall_curve = (period_totals / period_bases * 100)
print("\nOverall (all-cohort-weighted) retention curve, months 0-11:")
print(overall_curve.iloc[:12].round(2).to_string())

retention_pct.to_csv(f"{CLEANED}/cohort_retention_matrix.csv")
overall_curve.to_csv(f"{CLEANED}/cohort_retention_overall_curve.csv", header=["retention_pct"])

# ---- heatmap (blue sequential ramp, per palette) ----
matrix = retention_pct.iloc[:, :12].copy()
matrix.index = matrix.index.astype(str)
fig, ax = plt.subplots(figsize=(11, 9))
cmap = mcolors.LinearSegmentedColormap.from_list("seq_blue", ["#fcfcfb", "#9ec5f4", "#3987e5", "#184f95"])
im = ax.imshow(matrix.values, cmap=cmap, aspect="auto", vmin=0, vmax=min(60, np.nanmax(matrix.values[:, 1:]) if matrix.shape[1] > 1 else 100))
ax.set_xticks(range(matrix.shape[1]))
ax.set_xticklabels([f"M{i}" for i in matrix.columns])
ax.set_yticks(range(matrix.shape[0]))
ax.set_yticklabels(matrix.index, fontsize=8)
ax.set_title("Monthly Acquisition Cohorts — Retention % by Months Since First Order")
ax.set_xlabel("Months since first order")
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        v = matrix.values[i, j]
        if not np.isnan(v):
            ax.text(j, i, f"{v:.0f}", ha="center", va="center", fontsize=6.5,
                    color="#0b0b0b" if v < 30 else "#ffffff")
fig.colorbar(im, ax=ax, label="% of cohort retained", shrink=0.7)
fig.tight_layout()
fig.savefig(f"{CHARTS}/10_cohort_retention_heatmap.png", dpi=150)
plt.close(fig)

# ---- overall retention curve line chart ----
fig, ax = plt.subplots(figsize=(8, 4.5))
xs = overall_curve.index[:12]
ax.plot(xs, overall_curve.iloc[:12].values, color="#2a78d6", marker="o", linewidth=2.2)
ax.set_title("Overall Retention Curve (all cohorts, months since first order)")
ax.set_xlabel("Months since first order")
ax.set_ylabel("% of customers retained")
ax.set_ylim(0, max(30, overall_curve.iloc[1:12].max() * 1.3))
fig.tight_layout()
fig.savefig(f"{CHARTS}/11_overall_retention_curve.png", dpi=150)
plt.close(fig)

m1_retention = overall_curve.get(1, np.nan)
with open("../docs/05b_cohort_retention_summary.md", "w") as f:
    f.write("# Cohort / Retention Analysis Summary\n\nGenerated by `python/04_cohort_retention.py`.\n\n")
    f.write("Cohorts are defined by a customer's first-order month; `period_number` counts months since "
            "that first order. `M0` is always 100% by construction (every customer is in their own cohort "
            "in their acquisition month) — the numbers that matter are M1 onward.\n\n")
    f.write(f"- Month-1 retention (all cohorts, weighted): **{m1_retention:.1f}%** of customers who ordered "
            f"in their acquisition month placed another order the very next month.\n")
    f.write(f"- Retention decays further from there — see `data/cleaned/cohort_retention_overall_curve.csv` "
            f"for the full curve and `eda_charts/10_cohort_retention_heatmap.png` for the per-cohort view.\n")
    f.write(f"- This is consistent with the RFM finding that 42.5% of customers fall into Low Engagement and "
            f"the order-frequency distribution's fast decay — most customers do not return, and the ones "
            f"who do (Champions/Loyal) are the ones carrying disproportionate revenue.\n")
    f.write("- The dataset's reliable customer-date field (`order_date`) fully supports this analysis; no "
            "cohort had to be excluded for missing dates.\n")

print(f"\nMonth-1 overall retention: {m1_retention:.2f}%")
print("Saved cohort_retention_matrix.csv, overall curve, heatmap, and summary doc.")
